site_name: CAE32

nav:
  - Home: index.md
  - 'Hardware':
      - 'Pedales': 'pedales.md'
      - 'Volante': 'volante.md'
      - 'Palanca de cambios': 'palanca_de_cambios.md'
  - 'Changelog':
      - 'Pedales': 'changelog_hardware.md'
  - Firmware:
      - 'Firmware': 'firmware.md'
  - Sofware:
      - 'GUI gtk3': 'gui.md'
  - 'Tests':
      - 'Simulaci√≥n de dispositivo': sim_disp.md
theme: readthedocs
